[package]
name = "repose-material"
version = "0.6.1"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Material components for Repose"
[dependencies]
repose-core = { path = "../repose-core", version = "0.6.1" }
repose-ui = { path = "../repose-ui", version = "0.6.1" }
