[package]
name = "repose-canvas"
version = "0.6.3"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Immediate-mode canvas utilities for Repose"
[dependencies]
repose-core = { path = "../repose-core", version = "0.6.3" }
repose-ui = { path = "../repose-ui", version = "0.6.3" }
