[package]
name = "repose-text"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Text handling (wrappers around cosmic-text apis)"

[dependencies]
cosmic-text = { workspace = true }
fontdb = { workspace = true }
once_cell = "1"
ahash = "0.8"
