[package]
name = "showcase"
version = "0.3.5"
edition = "2024"
publish = false

[dependencies]
repose-core = { path = "../../crates/repose-core", version = "0.3.5" }
repose-ui = { path = "../../crates/repose-ui", version = "0.3.5" }
repose-platform = { path = "../../crates/repose-platform", version = "0.3.5", features = [
    "desktop",
] }
env_logger = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
