[package]
name = "repose-devtools"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"
description = "Repose developer tools for debugging."

[dependencies]
repose-core.workspace = true
log = { workspace = true }
