[package]
name = "repose-devtools"
version = "0.6.4"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Repose developer tools for debugging."

[dependencies]
repose-core = { path = "../repose-core", version = "0.6.4" }
log = { workspace = true }
