[package]
name = "animation_demo"
version = "0.3.0"
edition = "2024"
publish = false
description = "Animation demo for repose"

[dependencies]
compose-core = { path = "../../crates/compose-core", version = "0.3.0" }
compose-ui = { path = "../../crates/compose-ui", version = "0.3.0" }
compose-platform = { path = "../../crates/compose-platform", version = "0.3.0", features = [
    "desktop",
] }
env_logger = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
